/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CapabilityRouteImport } from './routes/capability'
import { Route as OrgRouteImport } from './routes/org'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PeoplePersonIdRouteImport } from './routes/people.$personId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilityRoute = CapabilityRouteImport.update({
  id: '/capability',
  path: '/capability',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRoute = OrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PeoplePersonIdRoute = PeoplePersonIdRouteImport.update({
  id: '/$personId',
  path: '/$personId',
  getParentRoute: () => PeopleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/auth': typeof AuthRoute
  '/capability': typeof CapabilityRoute
  '/org': typeof OrgRoute
  '/people': typeof PeopleRouteWithChildren
  '/settings': typeof SettingsRoute
  '/people/$personId': typeof PeoplePersonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/auth': typeof AuthRoute
  '/capability': typeof CapabilityRoute
  '/org': typeof OrgRoute
  '/people': typeof PeopleRouteWithChildren
  '/settings': typeof SettingsRoute
  '/people/$personId': typeof PeoplePersonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/auth': typeof AuthRoute
  '/capability': typeof CapabilityRoute
  '/org': typeof OrgRoute
  '/people': typeof PeopleRouteWithChildren
  '/settings': typeof SettingsRoute
  '/people/$personId': typeof PeoplePersonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actions'
    | '/auth'
    | '/capability'
    | '/org'
    | '/people'
    | '/settings'
    | '/people/$personId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions'
    | '/auth'
    | '/capability'
    | '/org'
    | '/people'
    | '/settings'
    | '/people/$personId'
  id:
    | '__root__'
    | '/'
    | '/actions'
    | '/auth'
    | '/capability'
    | '/org'
    | '/people'
    | '/settings'
    | '/people/$personId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionsRoute: typeof ActionsRoute
  AuthRoute: typeof AuthRoute
  CapabilityRoute: typeof CapabilityRoute
  OrgRoute: typeof OrgRoute
  PeopleRoute: typeof PeopleRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capability': {
      id: '/capability'
      path: '/capability'
      fullPath: '/capability'
      preLoaderRoute: typeof CapabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$personId': {
      id: '/people/$personId'
      path: '/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof PeoplePersonIdRouteImport
      parentRoute: typeof PeopleRoute
    }
  }
}

interface PeopleRouteChildren {
  PeoplePersonIdRoute: typeof PeoplePersonIdRoute
}

const PeopleRouteChildren: PeopleRouteChildren = {
  PeoplePersonIdRoute: PeoplePersonIdRoute,
}

const PeopleRouteWithChildren =
  PeopleRoute._addFileChildren(PeopleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionsRoute: ActionsRoute,
  AuthRoute: AuthRoute,
  CapabilityRoute: CapabilityRoute,
  OrgRoute: OrgRoute,
  PeopleRoute: PeopleRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
